# Generated by Django 3.1.6 on 2021-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dictionary',
                'unique_together': {('id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('parent', models.ManyToManyField(related_name='elements', to='dictionary_api.Dictionary')),
            ],
            options={
                'db_table': 'element',
            },
        ),
    ]
